---
kind: pipeline
type: docker
name: default

steps:
  - name: wait for docker
    image: docker:20.10.17-dind
    volumes:
      - name: dockersock
        path: /var/run
    commands:
      - while ! docker ps 2>&1 > /dev/null; do sleep 1; done

  - name: lint
    image: weastur/metalinter
    commands:
      - hadolint Dockerfile
      - shellcheck *.sh

  - name: build
    image: docker:20.10.17-dind
    volumes:
      - name: dockersock
        path: /var/run
    commands:
      - ./run.sh build

  - name: push
    image: docker:20.10.17-dind
    volumes:
      - name: dockersock
        path: /var/run
    when:
      branch:
        - main
      event:
        - push
    environment:
      DOCKER_TOKEN:
        from_secret: docker_token
    commands:
      - echo $DOCKER_TOKEN | docker login --username weastur --password-stdin
      - ./run.sh push

  - name: slack
    image: plugins/slack
    when:
      status:
        - success
        - failure
    settings:
      webhook:
        from_secret: slack_webhook

services:
  - name: docker
    image: docker:20.10.17-dind
    privileged: true
    volumes:
      - name: dockersock
        path: /var/run

volumes:
  - name: dockersock
    temp: {}

trigger:
  event:
    - pull_request
    - push
