---
name: Build and Push Docker Image

on:
  schedule:
    - cron: '0 0 * * 1'
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build and push (3.12.0b3-bookworm, 3.12-rc-bookworm 3.12.0b3, 3.12-rc)
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Dockerfile
        platforms: linux/amd64,linux/arm/v5,linux/arm/v7,linux/arm64,linux/386,linux/ppc64le,linux/s390x
        push: true
        tags: ['weastur/poetry:latest-python-3.12.0b3-bookworm', 'weastur/poetry:1.5.1-python-3.12.0b3-bookworm', 'weastur/poetry:latest-python-3.12-rc-bookworm 3.12.0b3', 'weastur/poetry:1.5.1-python-3.12-rc-bookworm 3.12.0b3', 'weastur/poetry:latest-python-3.12-rc', 'weastur/poetry:1.5.1-python-3.12-rc']
        build-args:
          - BASE_IMAGE_VERSION: 3.12.0b3-bookworm
          - POETRY_VERSION: 1.5.1
